Part I:
```{r}
K1 <-Class_Motivation
``` 

```{r}
K2 <- dplyr::select(K1, 2:6)
```

```{r}
K3 <- na.omit(K2)
```

```{r}
K3 <- scale(K3)
```

```{r}
fit <- kmeans(K3, 2)
```

```{r}
fit$cluster
```

```{r}
K4 <- data.frame(K3, fit$cluster)
```

```{r}
names(K4) <- c("1", "2", "3", "4", "5", "cluster")
```

```{r}
K5 <- tidyr::gather(K4, "week", "motivation", 1:5)
```

```{r}
K6 <- K5 %>% group_by(week, cluster)
K6 <- summarise(K6, avg = mean(motivation))
```

```{r}
K6$week <- as.numeric(K6$week)

K6$cluster <- as.factor(K6$cluster)
```

```{r}
ggplot(K6, aes(week, avg, colour = cluster)) + geom_line() + xlab("Week") + ylab("Average Motivation")
```

```{r}
K7 <- dplyr::count(K4, cluster)
```

Part II:
```{r}
A1 <- cluster_class_data
```

```{r}
A2 <- dplyr::select(A1,6:13,)
```

```{r}
A3 <- na.omit(A2)
```

```{r}
fit <-kmeans(A3,3)
```

```{r}
A4 <- data.frame(A3, fit$cluster)
```

```{r}
names(A4) <- c("1","2","3","4","5","6","7","8","cluster")
```

```{r}
A5 <- tidyr::gather(A4, "week", "QID", 1:5)
```

